### ISSUE TITLE
ZoomIn plugin not works with another plugin at the same time AMP360

### ISSUE THREAD

**Issue by mikezero84** [Azure-Samples/media-services-javascript-azure-media-player-zoom-plugin#1]
Following the plugins list for Azure media player in plugin gallery
https://learn.microsoft.com/en-us/azure/media-services/azure-media-player/azure-media-player-plugin-gallery

.Net core 6

`<!DOCTYPE html>
<html>

@section head {
    
    <script src="https://code.jquery.com/pep/0.4.1/pep.js"></script>
   
    
    <link href="https://amp.azure.net/libs/amp/2.3.11/skins/amp-default/azuremediaplayer.min.css" rel="stylesheet">
    <script src="https://amp.azure.net/libs/amp/2.3.11/azuremediaplayer.min.js"></script>
    <script src="~/js/amp/amp-360video.js"></script>
    <link href="~/js/amp/amp-zoom.css" rel="stylesheet">
    <script src="~/js/amp/amp-zoom.js"></script>
}

<body>
    <h1>Zoom Plugin Sample</h1>

    <video id="azuremediaplayer" playsinline crossorigin="anonymous"
       class="azuremediaplayer amp-default-skin amp-big-play-centered" 
        autoplay controls width="100%" height="100%"
       data-setup='{"nativeControlsForTouch": false, "logo": { "enabled": false }, "plugins": { "threeSixty": { }, "zoom": { } } }'>
        <source src="http://amssamples.streaming.mediaservices.windows.net/91492735-c523-432b-ba01-faba6c2206a2/AzureMediaServicesPromo.ism/manifest" type="application/vnd.ms-sstr+xml" />
        <p class="amp-no-js">
            To view this video please enable JavaScript, and consider upgrading to a web browser that supports HTML5 video
        </p>
    </video>

    @section script {
    <script>
        amp.options.flashSS.swf = "//amp.azure.net/libs/amp/latest/techs/StrobeMediaPlayback.2.0.swf"
        amp.options.silverlightSS.xap = "//amp.azure.net/libs/amp/latest/techs/SmoothStreamingPlayer.xap"
    </script>

    <script>
        var myPlayer = amp('azuremediaplayer', {
            "nativeControlsForTouch": false,
            autoplay: false,
            controls: true,
            poster: "",
            techOrder: ["azureHtml5JS", "html5"]
        }, function () {
            console.log('Good to go!');
            // add an event listener
            this.addEventListener('ended', function () {
                console.log('Finished!');
            });
        });

        myPlayer.src([{
            src: "https://amsbundletestussc-usso.streaming.media.azure.net/e416ec23-f431-4efe-8bf0-71212e2e2682/VID_20210611_100930.ism/manifest",
            type: "application/vnd.ms-sstr+xml"
        }]);
    </script>
}
</body>

</html>`

trying to use amp360 and ZoomIn plugins at the same time only works the 360 render but the zoomIn only appears the scroll bar  but if you try to zoom this one doesn't work

**Comment by gonzajet** [comment]
Hi, @mikezero84 
I reviewed the issue and found that Azure Media Player 360 plugin is working on a canvas that it places over the video. The Zoom plugins was not aware of this so it could not zoom in. 
I have created a PR that takes this into account and should fix this issue.
